---
title: "Применение средств и методов OSINT"
author: Голубенко Владимир Сергеевич
format: 
    md:
        output-file: README.md
---
# Применение средств и методов OSINT
Голубенко Владимир Сергеевич

Open source intelligence (OSINT) – разведывательная дисциплина,
включающая в себя поиск, выбор и сбор разведывательной информации из
общедоступных источников, а также её анализ.

Такими источниками информации могут быть:

-   поисковые машины – Google, Bing, Yandex…

-   специализированные поисковые системы – Shodan, intelx.io, Censys…

-   порталы открытых данных – Github Awesome Lists, https://opendata.digital.gov.ru/

-   материалы профильных конференций

-   социальные сети, профильные блоги и т.д.

-   официальные сайты компаний

## Цель работы

1.  Освоить базовые подходы процессов OSINT

2.  Освоить современные инструменты поиска и сбора информации

3.  Освоить инструменты совместной работы в ходе аналитической
    деятельности

## Задание

1.  Собрать информацию о компании "НПО Эшелон"

2.  Собрать информацию об основных специализированных технологиях,
    применяемых в средствах защиты информации.

3.  Собрать информацию о публичных сотрудниках, ведущих профильные
    технологические блоги, профили в социальных сетях и т.д.

4.  Сформировать представление о рынке отечественных решений ИБ

## Ход выполнения работы

### Основная информация о компании

Полное наименование компании – ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ЗЕКУРИОН РУС"

Место нахождения - 107023, город Москва, Электрозаводская ул, д. 24 стр. 1
Почтовый адрес – Электрозаводская ул., д. 24, Москва, 107023

ИНН - 7718676447

оргн - 1077762808683

[Источник](https://www.rusprofile.ru/id/2422463)

### Структура компании

Донской Дмитрий - Директор по развитию региональных продаж

Дорофеев Александр Владимирович - Директор по развитию бизнеса

Клянчин Александр Иванович - Руководитель отдела продаж

Марков Алексей Сергеевич - 	Президент

Пучкин Вадим Вячеславович - Менеджер по маркетингу

Цирлов Валентин Леонидович - 	Генеральный директор

Багдасарянц Александр Евгеньевич - Директор направления

Барабанов Александр Владимирович - Директор направления

Данилкович Алеся Геннадьевна - Маркетолог

[Источник](https://www.tadviser.ru/index.php/%D0%9A%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F:%D0%9D%D0%9F%D0%9E_%D0%AD%D1%88%D0%B5%D0%BB%D0%BE%D0%BD_%D0%90%D0%9E)

### Основные направления деятельности компании

1. AppChecker Cloud - Статический анализатор кода, предназначенный для автоматизированного поиска дефектов в исходном коде приложений, разработанных на C/C++, Java, PHP, C#.
2. СКАНЕР-ВС - Мобильное место администратора безопасности для мониторинга и анализа защищенности. Возможность применения как средство для проведения сертификационных и аттестационных испытаний.
3. РУБИКОН - Сертифицированный Межсетевой экран и система обнаружения вторжений для использования в автоматизированных системах военного назначения, в которых обрабатывается информация, составляющая государственную тайну.
4. РУБИКОН-А - Предназначен для использования в системах ГИС, ИСПДн и информационных систем, обрабатывающих информацию, содержащую сведения, составляющие государственную тайну.
5. РУБИКОН-К - Сертифицированный Межсетевой экран и система обнаружения вторжений для защиты ГИС, ИСПДн и информационных систем, обрабатывающих конфиденциальную информацию, включая персональные данные.
6. РУБИКОН-ОШ - Решение, предназначенное для однонаправленной передачи данных в автоматизированных системах военного назначения между сегментами разного уровня секретности на базе 2-х ПАК «Рубикон» с использованием специализированных оптических плат.
7. KOMRAD Enterprise SIEM - Отечественная SIEM-система позволяет осуществлять централизованный сбор событий ИБ, выявлять инциденты ИБ и оперативно на них реагировать.
Применение комплекса позволяет эффективно  выполнять требования, предъявляемые регуляторами к защите персональных данных, к обеспечению безопасности государственных информационных систем и контролю критической информационной инфраструктуры предприятия.
8. АК-ВС 3 - Средство сертификационных испытаний на отсутствие недекларированных возможностей (программных закладок), а также проведения анализа безопасности программного кода.
9. АК-ВС 2 - Средство сертификационных испытаний на отсутствие недекларированных возможностей (программных закладок), а также проведения анализа безопасности программного кода.
10. Пульсар - Генератор электромагнитного шума «Пульсар» предназначен для маскировки информативных побочных электромагнитных излучений и наводок (ПЭМИН) средств вычислительной техники и используется для защиты информации ограниченного доступа, в том числе сведений, составляющих государственную тайну любой категории до грифа «Совершенно секретно» включительно.
11. ПИК ЭШЕЛОН - Средство проведения инспекционного контроля

### Стек используемых технологий

Linux (RPM-based)

1С

JAVA

С++

LabVIEW

Iridium
 
Extron
 
Crestron
 
AMX

PostgreSQL

SQLite

Python

[Источник](https://npo-echelon.ru/about/vacancies/)

### Основные веб-сайты компании и её продуктов

[Основной сайт](https://npo-echelon.ru/)
[Сайт НПО Эшелон UTM ФСТЭК](https://npo-echelon.ru/fstek)(https://npo-echelon.ru/services/certification/)

### Публичные ресурсы компании

[Группа в ВКонтакте](https://vk.com/npo_echelon)
[Канал на Youtube](https://www.youtube.com/@EchelonSecurityRus)

## Выводы

Таким образом, с помощью процесса OSINT была получена информация о
компании Айдеко.

